import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { tresGenes } from './genes.js';
import { criarAudio } from './audio.js';

const ARENA = 38;
const MAX_E = 420;
const MAX_B = 900;
const MAX_X = 360;
const COLORS = { plankton: 0x39d98a, herb: 0x7ad151, pred: 0xe24b6a, tank: 0xd4a42a, split: 0x6ec8ff, boss: 0xb44cff, spore: 0xe8fff4, virus: 0x72ffb0, xp: 0x9dffc8 };
function mulberry(seed) { let t = seed >>> 0; return () => { t += 0x6D2B79F5; let r = Math.imul(t ^ (t >>> 15), 1 | t); r ^= r + Math.imul(r ^ (r >>> 7), 61 | r); return ((r ^ (r >>> 14)) >>> 0) / 4294967296; }; }
const WATER_VERT = `varying vec2 vUv; void main(){ vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }`;
const WATER_FRAG = `uniform float uTime; uniform vec3 uDeep; uniform vec3 uShallow; varying vec2 vUv;
float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453); }
float noise(vec2 p){ vec2 i=floor(p),f=fract(p); float a=hash(i),b=hash(i+vec2(1,0)),c=hash(i+vec2(0,1)),d=hash(i+vec2(1,1)); vec2 u=f*f*(3.0-2.0*f); return mix(a,b,u.x)+(c-a)*u.y*(1.0-u.x)+(d-b)*u.x*u.y; }
void main(){ vec2 uv=vUv*8.0; float n=noise(uv+vec2(uTime*0.07,-uTime*0.04)); n+=0.5*noise(uv*2.2-vec2(uTime*0.11,uTime*0.06)); float caust=pow(n,2.2); vec3 col=mix(uDeep,uShallow,caust); float rim=smoothstep(0.0,0.18,length(vUv-0.5)); col=mix(col,vec3(0.01,0.04,0.05),rim*0.55); gl_FragColor=vec4(col,1.0); }`;
export class Game {
  constructor(canvas){ this.canvas=canvas; this.audio=criarAudio(); this.keys={}; this.state='boot'; this.rng=mulberry(0xC0FFEE); this.elapsed=0; this.kills=0; this.wave=1; this.waveName='plâncton'; this.picked=[]; this._tmp=new THREE.Object3D(); this._c=new THREE.Color(); }
  boot(){
    this.scene=new THREE.Scene(); this.scene.fog=new THREE.FogExp2(0x041014,0.018); this.scene.background=new THREE.Color(0x041014);
    this.camera=new THREE.PerspectiveCamera(42,1,0.1,220); this.camera.position.set(0,34,28); this.camera.lookAt(0,0,0);
    this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance'});
    this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.75)); this.renderer.toneMapping=THREE.ACESFilmicToneMapping; this.renderer.toneMappingExposure=1.05;
    const light=new THREE.DirectionalLight(0xc8fff0,1.35); light.position.set(-18,40,12); this.scene.add(light); this.scene.add(new THREE.AmbientLight(0x1a3a44,0.55));
    this.fill=new THREE.PointLight(0x39d98a,18,60,2); this.fill.position.set(0,8,0); this.scene.add(this.fill);
    this.waterMat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uDeep:{value:new THREE.Color(0x062028)},uShallow:{value:new THREE.Color(0x1c6b6a)}},vertexShader:WATER_VERT,fragmentShader:WATER_FRAG});
    const water=new THREE.Mesh(new THREE.CircleGeometry(ARENA+6,80),this.waterMat); water.rotation.x=-Math.PI/2; water.position.y=-0.2; this.scene.add(water);
    const rim=new THREE.Mesh(new THREE.TorusGeometry(ARENA+0.4,0.35,10,80), new THREE.MeshStandardMaterial({color:0x0c3036,metalness:0.4,roughness:0.35,emissive:0x052022,emissiveIntensity:0.4})); rim.rotation.x=Math.PI/2; this.scene.add(rim);
    this.playerGroup=new THREE.Group();
    this.playerGroup.add(new THREE.Mesh(new THREE.IcosahedronGeometry(0.72,2), new THREE.MeshStandardMaterial({color:0xb8ffe0,emissive:0x1ea86a,emissiveIntensity:0.85,roughness:0.25})));
    this.playerSegs=[];
    for(let i=0;i<6;i++){ const seg=new THREE.Mesh(new THREE.CapsuleGeometry(0.16,0.7,4,8), new THREE.MeshStandardMaterial({color:0x39d98a,emissive:0x146b45,emissiveIntensity:0.6})); this.playerGroup.add(seg); this.playerSegs.push(seg); }
    this.scene.add(this.playerGroup);
    const eGeo=new THREE.CapsuleGeometry(0.28,0.55,3,6); const eMat=new THREE.MeshStandardMaterial({vertexColors:true,roughness:0.4,metalness:0.1});
    this.eMesh=new THREE.InstancedMesh(eGeo,eMat,MAX_E); this.eMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage); this.eMesh.instanceColor=new THREE.InstancedBufferAttribute(new Float32Array(MAX_E*3),3); this.scene.add(this.eMesh);
    this.bMesh=new THREE.InstancedMesh(new THREE.SphereGeometry(0.14,8,8), new THREE.MeshBasicMaterial({color:0xffffff}), MAX_B); this.bMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage); this.bMesh.instanceColor=new THREE.InstancedBufferAttribute(new Float32Array(MAX_B*3),3); this.scene.add(this.bMesh);
    this.xMesh=new THREE.InstancedMesh(new THREE.OctahedronGeometry(0.18,0), new THREE.MeshBasicMaterial({color:0x9dffc8}), MAX_X); this.xMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage); this.scene.add(this.xMesh);
    this.composer=new EffectComposer(this.renderer); this.composer.addPass(new RenderPass(this.scene,this.camera)); this.bloom=new UnrealBloomPass(new THREE.Vector2(1,1),0.55,0.7,0.25); this.composer.addPass(this.bloom); this.composer.addPass(new OutputPass());
    this._alloc(); this._bind(); this._resize(); window.addEventListener('resize',()=>this._resize()); this._raf=requestAnimationFrame(t=>this._frame(t));
  }
  _alloc(){ this.ex=new Float32Array(MAX_E); this.ez=new Float32Array(MAX_E); this.ehp=new Float32Array(MAX_E); this.er=new Float32Array(MAX_E); this.espd=new Float32Array(MAX_E); this.expv=new Float32Array(MAX_E); this.etype=new Uint8Array(MAX_E); this.eon=new Uint8Array(MAX_E); this.eburn=new Float32Array(MAX_E); this.bx=new Float32Array(MAX_B); this.bz=new Float32Array(MAX_B); this.bvx=new Float32Array(MAX_B); this.bvz=new Float32Array(MAX_B); this.bdmg=new Float32Array(MAX_B); this.blife=new Float32Array(MAX_B); this.bpierce=new Uint8Array(MAX_B); this.bon=new Uint8Array(MAX_B); this.bkind=new Uint8Array(MAX_B); this.xx=new Float32Array(MAX_X); this.xz=new Float32Array(MAX_X); this.xon=new Uint8Array(MAX_X); this.xval=new Float32Array(MAX_X); }
  _bind(){ window.addEventListener('keydown',e=>{this.keys[e.code]=true;}); window.addEventListener('keyup',e=>{this.keys[e.code]=false;}); }
  _resize(){ const w=innerWidth,h=innerHeight; this.camera.aspect=w/h; this.camera.updateProjectionMatrix(); this.renderer.setSize(w,h,false); this.composer.setSize(w,h); this.bloom.setSize(w,h); }
  start(){ this.audio.start(); this.rng=mulberry((performance.now()*1000)|0); this.state='run'; this.elapsed=0; this.kills=0; this.wave=1; this.waveName='plâncton'; this.picked=[]; this.spawnAcc=0; this.shotAcc=0; this.novaAcc=0; this.eyeAcc=0; this.virusAcc=0; this.hurtCd=0; this._b1=false; this._b2=false;
    this.player={x:0,z:0,hp:100,maxHp:100,speed:11,magnet:3.2,armor:0,regen:0,sporeCount:1,sporeRate:0.22,sporeDmg:14,sporeSpd:22,sporeLife:0.9,nova:false,novaR:3.2,novaDmg:22,novaCd:2.4,eye:false,eyeDmg:9,eyeCd:0.16,virus:false,virusN:1,virusCd:1.1,orbit:false,orbitN:2,xp:0,level:1,next:10,xpGain:1,crit:0.04,area:1,slow:0,burn:0,knock:2.2};
    this.eon.fill(0); this.bon.fill(0); this.xon.fill(0); this._hudGenes();
    document.getElementById('veil').classList.remove('show'); document.getElementById('dead').classList.remove('show'); document.getElementById('levelup').classList.remove('show'); document.getElementById('pause').classList.remove('show');
  }
  togglePause(){ if(this.state==='run'){ this.state='pause'; document.getElementById('pause').classList.add('show'); } else if(this.state==='pause'){ this.state='run'; document.getElementById('pause').classList.remove('show'); } }
  _frame(t){ const now=t*0.001; const dt=Math.min(0.033,(this._last?now-this._last:0.016)); this._last=now; if(this.state==='run') this.update(dt,now); this.draw(now); this.composer.render(); this._raf=requestAnimationFrame(x=>this._frame(x)); }
  update(dt){ const p=this.player; let mx=0,mz=0; if(this.keys.KeyW||this.keys.ArrowUp) mz-=1; if(this.keys.KeyS||this.keys.ArrowDown) mz+=1; if(this.keys.KeyA||this.keys.ArrowLeft) mx-=1; if(this.keys.KeyD||this.keys.ArrowRight) mx+=1; const len=Math.hypot(mx,mz)||1; p.x+=(mx/len)*p.speed*dt; p.z+=(mz/len)*p.speed*dt; const d0=Math.hypot(p.x,p.z); if(d0>ARENA-1.2){ p.x*=(ARENA-1.2)/d0; p.z*=(ARENA-1.2)/d0; } p.hp=Math.min(p.maxHp,p.hp+p.regen*dt); this.hurtCd=Math.max(0,this.hurtCd-dt); this.elapsed+=dt; this._waves(dt); this._weapons(dt); if(p.orbit){ const n=p.orbitN; for(let i=0;i<n;i++){ const a=this.elapsed*3.1+i*(Math.PI*2/n); this._aoe(p.x+Math.cos(a)*2.4,p.z+Math.sin(a)*2.4,0.7,18*dt);} } this._enemies(dt); this._bullets(dt); this._xp(dt); this._hud(); if(p.hp<=0) this._die(); }
  _waves(dt){ const t=this.elapsed; this.wave=1+Math.floor(t/45); const names=['plâncton','hera','predadores','tapete','lise','citadela','abismo']; this.waveName=names[Math.min(names.length-1,this.wave-1)]; this.spawnAcc+=dt*(0.55+t*0.018); while(this.spawnAcc>1){ this.spawnAcc-=1; const n=t>120?3:t>60?2:1; for(let i=0;i<n;i++) this._spawnEnemy(false);} if(Math.floor(t)===90&&!this._b1){this._b1=true;this._spawnEnemy(true);} if(Math.floor(t)===180&&!this._b2){this._b2=true;this._spawnEnemy(true);this._spawnEnemy(true);} }
  _spawnEnemy(boss){ let slot=-1; for(let i=0;i<MAX_E;i++) if(!this.eon[i]){slot=i;break;} if(slot<0) return; const ang=this.rng()*Math.PI*2, rad=ARENA*0.92; this.ex[slot]=Math.cos(ang)*rad; this.ez[slot]=Math.sin(ang)*rad; const t=this.elapsed; let type=0; const r=this.rng(); if(boss) type=5; else if(t>100&&r<0.12) type=4; else if(t>70&&r<0.22) type=3; else if(t>40&&r<0.38) type=2; else if(t>20&&r<0.55) type=1; const hp=boss?420+t*3:[18,32,28,90,22,420][type]*(1+t*0.012); this.ehp[slot]=hp; this.er[slot]=boss?1.8:[0.42,0.55,0.5,0.85,0.4,1.8][type]; this.espd[slot]=boss?3.2:[4.2,3.4,7.1,2.4,5.0,3.2][type]; this.expv[slot]=boss?28:[1,2,2,5,2,28][type]; this.etype[slot]=type; this.eburn[slot]=0; this.eon[slot]=1; }
  _nearest(x,z){ let best=-1,bd=1e9; for(let i=0;i<MAX_E;i++){ if(!this.eon[i]) continue; const d=(this.ex[i]-x)**2+(this.ez[i]-z)**2; if(d<bd){bd=d;best=i;} } return best; }
  _weapons(dt){ const p=this.player; this.shotAcc+=dt; while(this.shotAcc>=p.sporeRate){ this.shotAcc-=p.sporeRate; const tgt=this._nearest(p.x,p.z); let ax=1,az=0; if(tgt>=0){ax=this.ex[tgt]-p.x;az=this.ez[tgt]-p.z;} const L=Math.hypot(ax,az)||1; ax/=L; az/=L; const n=p.sporeCount; for(let k=0;k<n;k++){ const spread=(k-(n-1)/2)*0.14; const cs=Math.cos(spread),sn=Math.sin(spread); this._fire(p.x,p.z,(ax*cs-az*sn)*p.sporeSpd,(ax*sn+az*cs)*p.sporeSpd,p.sporeDmg,p.sporeLife,0,0);} this.audio.shoot(); } if(p.nova){ this.novaAcc+=dt; if(this.novaAcc>=p.novaCd){ this.novaAcc=0; this._aoe(p.x,p.z,p.novaR,p.novaDmg);} } if(p.eye){ this.eyeAcc+=dt; if(this.eyeAcc>=p.eyeCd){ this.eyeAcc=0; const tgt=this._nearest(p.x,p.z); if(tgt>=0) this._hurt(tgt,p.eyeDmg,0,0);} } if(p.virus){ this.virusAcc+=dt; if(this.virusAcc>=p.virusCd){ this.virusAcc=0; const tgt=this._nearest(p.x,p.z); if(tgt>=0){ for(let k=0;k<p.virusN;k++){ const ax=this.ex[tgt]-p.x,az=this.ez[tgt]-p.z; const L=Math.hypot(ax,az)||1; this._fire(p.x,p.z,(ax/L)*16,(az/L)*16,p.sporeDmg*0.85,1.4,1,1);} } } } }
  _fire(x,z,vx,vz,dmg,life,pierce,kind){ for(let i=0;i<MAX_B;i++) if(!this.bon[i]){ this.bx[i]=x;this.bz[i]=z;this.bvx[i]=vx;this.bvz[i]=vz;this.bdmg[i]=dmg;this.blife[i]=life;this.bpierce[i]=pierce;this.bkind[i]=kind;this.bon[i]=1;return;} }
  _aoe(x,z,r,dmg){ const r2=r*r; for(let i=0;i<MAX_E;i++){ if(!this.eon[i]) continue; const dx=this.ex[i]-x,dz=this.ez[i]-z; if(dx*dx+dz*dz<=r2) this._hurt(i,dmg,dx,dz);} }
  _hurt(i,dmg,kx,kz){ const p=this.player; let d=dmg; if(this.rng()<p.crit) d*=2.4; this.ehp[i]-=d; this.eburn[i]=Math.max(this.eburn[i], p.burn>0?2.4:0); const L=Math.hypot(kx,kz)||1; this.ex[i]+=(kx/L)*p.knock*0.08; this.ez[i]+=(kz/L)*p.knock*0.08; if(this.ehp[i]<=0) this._kill(i); }
  _kill(i){ this.eon[i]=0; this.kills++; this._dropXp(this.ex[i],this.ez[i],this.expv[i]); if(this.etype[i]===4){ for(let k=0;k<2;k++) this._spawnEnemy(false);} }
  _dropXp(x,z,v){ for(let i=0;i<MAX_X;i++) if(!this.xon[i]){ this.xx[i]=x;this.xz[i]=z;this.xval[i]=v;this.xon[i]=1;return;} }
  _enemies(dt){ const p=this.player; for(let i=0;i<MAX_E;i++){ if(!this.eon[i]) continue; const ax=p.x-this.ex[i], az=p.z-this.ez[i]; const L=Math.hypot(ax,az)||1; const slow=1/(1+p.slow); this.ex[i]+=(ax/L)*this.espd[i]*slow*dt; this.ez[i]+=(az/L)*this.espd[i]*slow*dt; if(this.eburn[i]>0){ this.eburn[i]-=dt; this.ehp[i]-=p.burn*dt; if(this.ehp[i]<=0){ this._kill(i); continue; } } if(L<this.er[i]+0.7 && this.hurtCd<=0){ p.hp-=([7,10,14,16,9,22][this.etype[i]])*(1-p.armor); this.hurtCd=0.55; this.audio.hit(); } } }
  _bullets(dt){ const p=this.player; const rad=0.38*p.area; for(let i=0;i<MAX_B;i++){ if(!this.bon[i]) continue; this.bx[i]+=this.bvx[i]*dt; this.bz[i]+=this.bvz[i]*dt; this.blife[i]-=dt; if(this.blife[i]<=0||Math.hypot(this.bx[i],this.bz[i])>ARENA+2){ this.bon[i]=0; continue;} if(this.bkind[i]===1){ const tgt=this._nearest(this.bx[i],this.bz[i]); if(tgt>=0){ const ax=this.ex[tgt]-this.bx[i],az=this.ez[tgt]-this.bz[i]; const L=Math.hypot(ax,az)||1; this.bvx[i]+=(ax/L)*48*dt; this.bvz[i]+=(az/L)*48*dt; } } for(let j=0;j<MAX_E;j++){ if(!this.eon[j]) continue; const dx=this.ex[j]-this.bx[i], dz=this.ez[j]-this.bz[i]; const rr=this.er[j]+rad; if(dx*dx+dz*dz<rr*rr){ this._hurt(j,this.bdmg[i],dx,dz); if(!this.bpierce[i]){ this.bon[i]=0; break; } } } } }
  _xp(dt){ const p=this.player; const mag2=p.magnet*p.magnet; for(let i=0;i<MAX_X;i++){ if(!this.xon[i]) continue; let dx=p.x-this.xx[i], dz=p.z-this.xz[i]; const d2=dx*dx+dz*dz; if(d2<mag2){ const L=Math.sqrt(d2)||1; this.xx[i]+=(dx/L)*16*dt; this.xz[i]+=(dz/L)*16*dt; dx=p.x-this.xx[i]; dz=p.z-this.xz[i]; } if(dx*dx+dz*dz<0.55){ this.xon[i]=0; p.xp+=this.xval[i]*p.xpGain; this.audio.xp(); while(p.xp>=p.next){ p.xp-=p.next; p.level+=1; p.next=Math.floor(10*Math.pow(1.22,p.level-1)); this._levelUp(); } } } }
  _levelUp(){ this.state='level'; this.audio.level(); const picks=tresGenes(this.rng); const row=document.getElementById('picks'); row.innerHTML=''; picks.forEach(g=>{ const b=document.createElement('button'); b.className='pick'; b.innerHTML=`<em>${g.tag}</em><strong>${g.nome}</strong><span>${g.desc}</span>`; b.onclick=()=>{ g.apply(this.player); this.picked.push(g.nome); this._hudGenes(); this.audio.pick(); document.getElementById('levelup').classList.remove('show'); this.state='run'; }; row.appendChild(b); }); document.getElementById('levelup').classList.add('show'); }
  _die(){ this.state='dead'; this.audio.dead(); const m=Math.floor(this.elapsed/60); const s=String(Math.floor(this.elapsed%60)).padStart(2,'0'); document.getElementById('recap').textContent=`${m}:${s} no tanque · ${this.kills} lisados · nível ${this.player.level} · ${this.picked.join(', ')||'sem mutações'}`; document.getElementById('dead').classList.add('show'); }
  _hud(){ const p=this.player; const m=Math.floor(this.elapsed/60); const s=String(Math.floor(this.elapsed%60)).padStart(2,'0'); document.getElementById('clock').textContent=`${m}:${s}`; document.getElementById('kills').textContent=`${this.kills} mortes`; document.getElementById('hpFill').style.transform=`scaleX(${Math.max(0,p.hp/p.maxHp)})`; document.getElementById('hpTxt').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`; document.getElementById('xpFill').style.transform=`scaleX(${p.xp/p.next})`; document.getElementById('xpTxt').textContent=`nv ${p.level}`; document.getElementById('wave').textContent=`onda ${this.wave} · ${this.waveName}`; }
  _hudGenes(){ document.getElementById('geneList').innerHTML=this.picked.slice(-8).map(n=>`<b>${n}</b>`).join(''); }
  draw(now){ this.waterMat.uniforms.uTime.value=now; const p=this.player||{x:0,z:0}; this.playerGroup.position.set(p.x,0.7,p.z); this.playerGroup.rotation.y=now*0.7; this.playerSegs.forEach((seg,i)=>{ const a=now*1.4+i*(Math.PI*2/6); seg.position.set(Math.cos(a)*1.15,0.1,Math.sin(a)*1.15); seg.rotation.z=Math.PI/2; seg.rotation.y=a; }); this.fill.position.set(p.x,7,p.z); this.camera.position.x+=(p.x*0.35-this.camera.position.x)*0.04; this.camera.position.z+=(p.z*0.35+28-this.camera.position.z)*0.04; this.camera.lookAt(p.x,0,p.z); const tmp=this._tmp; let shown=0; for(let i=0;i<MAX_E;i++){ if(!this.eon[i]) continue; tmp.position.set(this.ex[i], this.er[i]*0.7, this.ez[i]); const s=this.er[i]*2.1; tmp.scale.set(s,s,s); tmp.rotation.set(Math.PI/2,0,now+i); tmp.updateMatrix(); this.eMesh.setMatrixAt(shown,tmp.matrix); this._c.setHex([COLORS.plankton,COLORS.herb,COLORS.pred,COLORS.tank,COLORS.split,COLORS.boss][this.etype[i]]); this.eMesh.setColorAt(shown,this._c); shown++; } this.eMesh.count=shown; this.eMesh.instanceMatrix.needsUpdate=true; if(this.eMesh.instanceColor) this.eMesh.instanceColor.needsUpdate=true; shown=0; for(let i=0;i<MAX_B;i++){ if(!this.bon[i]) continue; tmp.position.set(this.bx[i],0.6,this.bz[i]); tmp.scale.setScalar(this.bkind[i]?1.4:1); tmp.rotation.set(0,0,0); tmp.updateMatrix(); this.bMesh.setMatrixAt(shown,tmp.matrix); this._c.setHex(this.bkind[i]?COLORS.virus:COLORS.spore); this.bMesh.setColorAt(shown,this._c); shown++; } this.bMesh.count=shown; this.bMesh.instanceMatrix.needsUpdate=true; if(this.bMesh.instanceColor) this.bMesh.instanceColor.needsUpdate=true; shown=0; for(let i=0;i<MAX_X;i++){ if(!this.xon[i]) continue; tmp.position.set(this.xx[i],0.45+Math.sin(now*4+i)*0.08,this.xz[i]); tmp.scale.setScalar(0.9); tmp.rotation.set(now,now,0); tmp.updateMatrix(); this.xMesh.setMatrixAt(shown,tmp.matrix); shown++; } this.xMesh.count=shown; this.xMesh.instanceMatrix.needsUpdate=true; }
}
